--showimage: new option

diff --git a/align b/align
--- a/align
+++ b/align
@@ -1,6 +1,6 @@
 #! /bin/bash
 # align - align image stack with focus-stack
-
+#
 usage() {
   echo "
 align - align image stack
@@ -15,18 +15,32 @@ Options:
  --rotate DEGREE           Rotate images clockwise by degree DEGREE.
  --contrast [=yes|no]      Correct contrast and exposure differences.
  --whitebalance [=yes|no]  Correct white balance differences.
+ -V, --showimage           Show aligned images in image viewer geeqie.
 
 Depends on:
  - focus-stack from Petteri Aimonen:
    https://github.com/PetteriAimonen/focus-stack
  - ImageMagick
+ - geeqie (optional)
+
+NOTE: You might need to remove the orientation tag of the source images first.
+Possible tool and command: 
+  exiftool -n -Orientation=0 -overwrite_original IMAGES
 "
 }
 digitonly() {
   echo "${1//[^0-9.]/}"
 }
+printsameline() {
+  # print $1 without newline at begin of current line
+  echo -ne "${1:-}\033[0K\r" >&2
+}
+showimage() {
+  [ "$Showimageprocessing" = "yes" ] && geeqie -t -r --File:"${1:-}" 2>/dev/null &
+  return 0
+}
 align_focusstack() {
-  local Log Line Image Outputimage Options= Command
+  local Log Line Image Outputimage Options= Command Count
   local X Y W H Lmax=0 Tmax=0 Rmin=10000000 Bmin=10000000
 
   # align with focus-stack
@@ -52,9 +66,14 @@ align_focusstack() {
   H="$((Bmin-Tmax-1))"
 
   # crop aligned images to valid area
-  while read Line; do
-    Image="${Line#*"task: Save "}"
+  Count="0"
+  while read Image; do
+    Count="$((Count+1))"
+    Image="$(basename "$Image")"
+    Image="$Destinationdir/$Image"
     Outputimage="$(rev <<< "$Image" | cut -d. -f2- | rev).tif"
+
+    printsameline "align: Cropping image $Count / $Imagenumber $Outputimage"
 
     Command="
 $Magickbin
@@ -72,8 +91,10 @@ $Magickbin
   -exit"
     $Command
 
+    showimage "$Outputimage"
     [ "$Image" != "$Outputimage" ] && rm "$Image"
-  done < <(grep "task: Save" <<< "$Log")
+  done <<< "$Sourceimagelist"
+  echo ""
 
   return 0
 }
@@ -81,8 +102,10 @@ declare_variables() {
   # Global variables with default values
   Contrast="no"
   Destinationdir="./aligned"
+  Imagenumber=""
   Magickbin=""
   Rotation="0"
+  Showimageprocessing=""
   Sourceimagelist=""
   Whitebalance="no"
   return 0
@@ -90,8 +113,8 @@ declare_variables() {
 parse_options() {
   local Shortoptions Longoptions Parsedoptions Terminate=
 
-  Shortoptions=""
-  Longoptions="contrast::,help,output:,rotate:,whitebalance::"
+  Shortoptions="V"
+  Longoptions="contrast::,help,output:,rotate:,showimage,whitebalance::"
 
   Parsedoptions="$(getopt --options "$Shortoptions" --longoptions "$Longoptions" --name "$0" -- "$@")"
   eval set -- "$Parsedoptions"
@@ -102,12 +125,16 @@ parse_options() {
       --help)         usage ; Terminate="yes" ;;
       --output)       Destinationdir="${2:-$Destinationdir}" ; shift ;;
       --rotate)       Rotation="${2:-0}" ; shift ;;
+      -V|--showimage) Showimageprocessing="yes" ;;
       --whitebalance) Whitebalance="${2:-yes}" ; shift ;;
       --) ;;
       *)
         Sourceimagelist="$Sourceimagelist
 ${1:-}"
-        [ -f "${1:-}" ] || error "File not found: ${1:-}"
+        [ -f "${1:-}" ] || {
+          echo "File not found: ${1:-}" >&2
+          Terminate="yes"
+        }
       ;;
     esac
     shift
@@ -115,6 +142,7 @@ ${1:-}"
 
   Sourceimagelist="$(grep .  <<< "$Sourceimagelist")"
   Sourceimagelist="$(sort -V <<< "$Sourceimagelist")"
+  Imagenumber="$(grep -c .   <<< "$Sourceimagelist")"
 
   [ "$Terminate" ] && exit 0
   return 0
@@ -135,6 +163,12 @@ main() {
   [ -z "$Magickbin" ] && {
     echo "Error: imagemagick not found." >&2
     return 1
+  }
+
+  # -V, --showimage
+  [ "$Showimageprocessing" = "yes" ] && {
+    command -v geeqie >/dev/null || error "-V, --showimage: geeqie not found."
+    geeqie -t -r --File:"$(head -n1 <<< "$Sourceimagelist")" 2>/dev/null
   }
 
   # run
