loop until cancel or error

diff --git a/camcfg b/camcfg
--- a/camcfg
+++ b/camcfg
@@ -2,14 +2,14 @@
 # gphoto2 configuration with shell dialog
 
 note() {
-  echo "${Colgreen}Note:${Colnorm} $*" >&2
+  echo "camcfg: $*" >&2
 }
 failure() {
-  echo "${Colred}FAILURE:${Colnorm} $*" >&2
+  echo "camcfg FAILURE: $*" >&2
 }
 gphoto2_wrap() {
   #note "gphoto2 $@"
-  gphoto2 $@ || {
+  gphoto2 "$@" || {
     failure "gphoto2 failed. Is the camera plugged in and turned on?"
     return 1
   }
@@ -26,12 +26,6 @@ gphoto2_switch_config() {
 
   local Choicecount Configlabel Configtype Configcurrent 
   local Dumpline Dumplineleft Dumplineright
-  
-  # Derzeitige Konfiguration auslesen und speichern
-  gphoto2_wrap --get-config $1 > $Kameradumpfile || {
-    failure "Fehler: Konfiguration der Kamera für $1 konnte nicht gelesen werden"
-    return 1
-  }
   
   # Konfiguration parsen
   while read Dumpline ; do
@@ -105,7 +99,7 @@ gphoto2_get_config() {
     *)          Showall="no" ;;
   esac
 
-  case $1 in
+  case "${1:-}" in
     "") # Keine einzelne Einstellung angegeben: Alle RADIO und MENU Einstellungen anzeigen
       gphoto2_wrap --list-all-config > $Kameradumpfile || {
         failure "Konnte Kamera nicht auslesen"
@@ -141,7 +135,7 @@ ${Configentry}§${Configlabel}§${Configcurrent}"
           *) [ "$(cut -c1 <<< "$Dumpline")" = "/" ] && Configentry="$(basename "$Dumpline")" ;;
         esac
         
-      done <$Kameradumpfile
+      done < "$Kameradumpfile"
       echo ""
   
       # Ergebnis in eine übersichtliche Tabelle verwandeln
@@ -159,141 +153,156 @@ ${Configentry}§${Configlabel}§${Configcurrent}"
       ;;
   esac
 }
-gphoto2_config_dialog() {
-  ## Funktion: Dialogboxen zur Konfiguration der Kamera erzeugen
-  # $1   ENTRY, der zu konfigurieren ist. Wenn leer, alle Configentrys zur Auswahl anbieten
-  local Configentry= Count= Dialogoptions= Line=
-
-  Configentry=$1
+gphoto2_configdialog_main() {
+  # Show overview dialog with all configurable entrys
   
-  # Auswahl aus allen Konfiguartionsmöglichkeiten anbieten
-  [ -z "$Configentry" ] && {
-    gphoto2_wrap --list-all-config > $Kameradumpfile || {
-      failure "Could not read camera configuration."
-      return 1
-    }
-    
-    declare -i Count="0"
-    while read -r Line ; do
-      Configentry[$Count]="$(basename $Line)"
-      Count=$Count+1
-    done < <(look "/" $Kameradumpfile)
-
-    declare -i Count="0"
-    while read -r Line ; do
-      LABEL[$Count]="$(cut -d ' ' -f2- <<<"$Line")"
-      Count=$Count+1
-    done < <(look "Label:" $Kameradumpfile)
+  local Configentry Count Dialogoptions Dialogtitle Line
+  local ENTRY LABEL TYPE CURRENT
   
-    declare -i Count="0"
-    while read -r Line ; do
-      TYPE[$Count]="$(cut -d ' ' -f2- <<<"$Line")"
-      Count=$Count+1
-    done < <(look "Type:" $Kameradumpfile)
+  note "Reading config entrys of camera, please wait."
+  gphoto2_wrap --list-all-config > "$Kameradumpfile" || {
+    failure "Could not read camera configuration."
+    return 1
+  }
+      
+  declare -i Count="0"
+  while read -r Line ; do
+    ENTRY[$Count]="$(basename $Line)"
+    Count=$Count+1
+  done < <(look "/" $Kameradumpfile)
+
+  declare -i Count="0"
+  while read -r Line ; do
+    LABEL[$Count]="$(cut -d ' ' -f2- <<<"$Line")"
+    Count=$Count+1
+  done < <(look "Label:" $Kameradumpfile)
+  
+  declare -i Count="0"
+  while read -r Line ; do
+    TYPE[$Count]="$(cut -d ' ' -f2- <<<"$Line")"
+    Count=$Count+1
+  done < <(look "Type:" $Kameradumpfile)
     
-    declare -i Count="0"
-    while read -r Line ; do
-      CURRENT[$Count]="$(cut -d ' ' -f2- <<< "$Line")"
-      Count=$Count+1
-    done < <(look "Current:" $Kameradumpfile)
+  declare -i Count="0"
+  while read -r Line ; do
+    CURRENT[$Count]="$(cut -d ' ' -f2- <<< "$Line")"
+    Count=$Count+1
+  done < <(look "Current:" $Kameradumpfile)
       
-    # Optionen sortieren, Type RADIO zuerst
-    :> $Kameradumpfile
-    while [ "$Count" -ge "1" ] ; do
-      Count=$Count-1
-      case ${TYPE[$Count]} in
-        RADIO|MENU) echo -n "AAAA " >> $Kameradumpfile ;;
-        TOGGLE) echo -n "BBBB " >> $Kameradumpfile ;;
-        TEXT) echo -n "DDDD " >> $Kameradumpfile ;;
-        DATE) echo -n "EEEE " >> $Kameradumpfile ;;
-        *) echo -n "CCCC " >> $Kameradumpfile ;;
-      esac
-      echo "'${Configentry[$Count]}' '${LABEL[$Count]}§${TYPE[$Count]}§${CURRENT[$Count]}'" >> $Kameradumpfile
-    done
-    while read -r Line ; do
-      Dialogoptions="$Dialogoptions $(echo $Line | cut -d ' ' -f2-)"
-    done < <(sort -V $Kameradumpfile)
-      
-    Configentry=$(eval dialog --column-separator '§' --menu '"Kamera Konfiguration auswählen"' 40 120 30 $Dialogoptions 3>&1 1>&2 2>&3 3>&-)
-  }
+  # Sort options, type RADIO first
+  :> $Kameradumpfile
+  while [ "$Count" -ge "1" ] ; do
+    Count=$Count-1
+    case ${TYPE[$Count]} in
+      RADIO|MENU) echo -n "AAAA " >> "$Kameradumpfile" ;;
+      TOGGLE)     echo -n "BBBB " >> "$Kameradumpfile" ;;
+      TEXT)       echo -n "DDDD " >> "$Kameradumpfile" ;;
+      DATE)       echo -n "EEEE " >> "$Kameradumpfile" ;;
+      *)          echo -n "CCCC " >> "$Kameradumpfile" ;;
+    esac
+    echo "'${ENTRY[$Count]}' '${LABEL[$Count]}§${TYPE[$Count]}§${CURRENT[$Count]}'" >> "$Kameradumpfile"
+  done
+  while read -r Line ; do
+    Dialogoptions="$Dialogoptions $(echo $Line | cut -d ' ' -f2-)"
+  done < <(sort -V $Kameradumpfile)
+  
+  Dialogtitle="Choose camera configuration entry."
+  Configentry=$(eval dialog --column-separator '§' --menu "'$Dialogtitle'" 40 120 30 $Dialogoptions 3>&1 1>&2 2>&3 3>&-)
 
-  # Einzelne Konfiguration ändern
-  [ -n "$Configentry" ] && {
-    note "Lese Konfiguration von $Configentry von der Kamera, bitte warten ..."
-    gphoto2_wrap --get-config $Configentry > $Kameradumpfile || {
-      failure "Fehler: Konfiguration der Kamera konnte nicht gelesen werden"
-      return 1
-    }
-
-      INDEX="0"
-      Dialogoptions=""
-      LABEL=`look "Label:" $Kameradumpfile | cut -d ' ' -f2-`
-      TYPE=`look "Type:" $Kameradumpfile | cut -d ' ' -f2-`
-      CURRENT=`look "Current:" $Kameradumpfile | cut -d ' ' -f2-`
-      while read -r Line ; do
-        CHOICE[$INDEX]=`echo -n $Line | cut -d ' ' -f3-`
-        Dialogoptions="$Dialogoptions $INDEX '${CHOICE[$INDEX]}'"
-        if [ "${CHOICE[$INDEX]}" = "$CURRENT" ] ; then Dialogoptions="$Dialogoptions on"
-        else Dialogoptions="$Dialogoptions off" ; fi
-        INDEX=$[$INDEX+1]
-      done < <(look "Choice:" $Kameradumpfile)
-
-      case $TYPE in
-      RADIO|MENU)
-        INDEX=$(eval dialog --radiolist '"Auswahl für $Configentry: $LABEL \nDerzeit: $CURRENT"' 40 120 30 $Dialogoptions 3>&1 1>&2 2>&3 3>&-)
-        if test "$INDEX" ; then 
-          note "Setze $Configentry=$INDEX => $LABEL ${CHOICE[$INDEX]}"
-          gphoto2_wrap --set-config-index $Configentry=$INDEX
-        fi
-        ;;
-      TEXT)
-        CHOICE=$(eval dialog --inputbox '"Neuer Wert für $Configentry: $LABEL \nDerzeit: $CURRENT"' 12 78 '"$CURRENT"' 3>&1 1>&2 2>&3 3>&-)
-        if test "$CHOICE" ; then
-          note "Ändere $Configentry: $LABEL von $CURRENT auf $CHOICE"
-          gphoto2_wrap --set-config-value "$Configentry=$CHOICE"
-        fi
-        ;;
-      TOGGLE)
-        Dialogoptions="1 Ein off 0 Aus off"
-        #eval echo  --radiolist '"Schalter: $Configentry: $LABEL' 15 70 2 $Dialogoptions
-        CHOICE=$(eval dialog --radiolist '"Schalter: $Configentry: $LABEL"' 15 70 2 $Dialogoptions 3>&1 1>&2 2>&3 3>&-)
-        if test "$CHOICE" ; then 
-          note "Stelle Schalter $Configentry auf $CHOICE"
-          gphoto2_wrap --set-config-value $Configentry=$CHOICE 
-        fi
-        ;;
-      *)
-        DIALOGTEXT="Unbekannter Konfigurationstyp $TYPE. Ausgabe von get-config $Configentry:\n"
-        while read -r LINE ; do
-          DIALOGTEXT=$DIALOGTEXT$LINE"\n"
-        done < $Kameradumpfile
-        CHOICE=$(eval dialog --inputbox '"$DIALOGTEXT"' 12 78 '"$CURRENT"' 3>&1 1>&2 2>&3 3>&-)
-        if test -n "$CHOICE" ; then 
-          note "Setze $Configentry auf $CHOICE"
-          gphoto2_wrap --set-config-value $Configentry=$CHOICE
-        fi
-        ;;
-      esac
-  }
+  [ -z "$Configentry" ] && return 1
+  echo "$Configentry"
+  return 0
 }
-declare_variables() {
-  # Terminal colors used for messages
-  Esc="$(printf '\033')"
-  Colblue="${Esc}[35m"
-  Colyellow="${Esc}[33m"
-  Colgreen="${Esc}[32m"
-  Colgreenbg="${Esc}[42m"
-  Colred="${Esc}[31m"
-  Colredbg="${Esc}[41m"
-  Coluline="${Esc}[4m"
-  Colnorm="${Esc}[0m"
+gphoto2_configdialog_entry() {
+  # Show config dialog for single entry
+  # $1   config entry
+  local Configentry Count Dialogoptions Line
+  local INDEX LABEL TYPE CURRENT CHOICE
+
+  Configentry="$1"
+
+  [ -z "$Configentry" ] && return 1
+
+  note "Reading config of $Configentry from camera, please wait."
+  gphoto2_wrap --get-config $Configentry > $Kameradumpfile || {
+    failure "Could not read configuration of $Configentry"
+    return 1
+  }
+
+  INDEX="0"
+  Dialogoptions=""
+  LABEL="$(look   "Label:"   $Kameradumpfile | cut -d ' ' -f2-)"
+  TYPE="$(look    "Type:"    $Kameradumpfile | cut -d ' ' -f2-)"
+  CURRENT="$(look "Current:" $Kameradumpfile | cut -d ' ' -f2-)"
   
-  Kameradumpfile=/tmp/camcfg.dump
+  while read -r Line ; do
+    #CHOICE[$INDEX]=`echo -n $Line | cut -d ' ' -f3-`
+    CHOICE[$INDEX]="$(cut -d ' ' -f3- <<< "$Line")"
+    Dialogoptions="$Dialogoptions $INDEX '${CHOICE[$INDEX]}'"
+    [ "${CHOICE[$INDEX]}" = "$CURRENT" ] && Dialogoptions="$Dialogoptions on" || Dialogoptions="$Dialogoptions off"
+    INDEX="$((INDEX+1))"
+  done < <(look "Choice:" "$Kameradumpfile")
+
+  case $TYPE in
+    RADIO|MENU)
+      INDEX="$(eval dialog --radiolist '"Choice for $Configentry: $LABEL \nCurrent: $CURRENT"' 40 120 30 $Dialogoptions 3>&1 1>&2 2>&3 3>&-)"
+      [ "$INDEX" ] && { 
+        note "Setting $Configentry=$INDEX => $LABEL ${CHOICE[$INDEX]}"
+        gphoto2_wrap --set-config-index "$Configentry=$INDEX" || return 1
+      }
+    ;;
+    TEXT)
+      CHOICE="$(eval dialog --inputbox '"New value for $Configentry: $LABEL \nCurrent: $CURRENT"' 12 78 '"$CURRENT"' 3>&1 1>&2 2>&3 3>&-)"
+      [ "$CHOICE" ] && {
+        note "Setting $Configentry: $LABEL from $CURRENT to $CHOICE"
+        gphoto2_wrap --set-config-value "$Configentry=$CHOICE" || return 1
+      }
+    ;;
+    TOGGLE)
+      Dialogoptions="1 Ein off 0 Aus off"
+      #eval echo  --radiolist '"Schalter: $Configentry: $LABEL' 15 70 2 $Dialogoptions
+      CHOICE="$(eval dialog --radiolist '"Switch: $Configentry: $LABEL"' 15 70 2 $Dialogoptions 3>&1 1>&2 2>&3 3>&-)"
+      [ "$CHOICE" ] && {
+        note "Switching $Configentry to $CHOICE"
+        gphoto2_wrap --set-config-value "$Configentry=$CHOICE" || return 1
+      }
+    ;;
+    *)
+      DIALOGTEXT="Unknown configuration type $TYPE. Output of get-config $Configentry:\n"
+      while read -r LINE ; do
+        DIALOGTEXT="${DIALOGTEXT}${LINE}\n"
+      done < "$Kameradumpfile"
+      CHOICE="$(eval dialog --inputbox '"$DIALOGTEXT"' 12 78 '"$CURRENT"' 3>&1 1>&2 2>&3 3>&-)"
+      [ "$CHOICE" ] && { 
+        note "Setting $Configentry to $CHOICE"
+        gphoto2_wrap --set-config-value "$Configentry=$CHOICE" || return 1
+      }
+    ;;
+  esac
+  
+  return 0
 }
 main() {
-  declare_variables
+  local Kameradumpfile Configentry
+  
+  Configentry="$@"
+  Kameradumpfile=/tmp/camcfg.dump
   :> $Kameradumpfile
-  gphoto2_config_dialog "$@"
+  Showall=no
+  
+  while :; do
+    # Main dialog
+    [ -z "$Configentry" ] && {
+      Configentry="$(gphoto2_configdialog_main)"
+    }
+    # Single entry dialog
+    [ -z "$Configentry" ] && break
+    gphoto2_configdialog_entry "$Configentry" || break
+    Configentry=""
+  done
+  
   rm $Kameradumpfile
+  return 0
 }
+#gphoto2_get_config "$@"
 main "$@"
