bugfix: finalblur before alpha

diff --git a/imfuse b/imfuse
--- a/imfuse
+++ b/imfuse
@@ -1,7 +1,7 @@
 #! /bin/bash
 
 # imfuse
-Version="0.6.8-beta"
+Version="0.6.9-beta"
 
 # ToDo:
 #
@@ -22,11 +22,8 @@ Version="0.6.8-beta"
 # check exiftransfer / damaged one Beerenwanze or Spinne image
 #
 # stackfuser: 
-# fakehdr is missing
-# exiftransfer wrong after reverse-order or block-evaluate
-#
-# imgview:
-# layered tifs
+# BUG fakehdr is missing
+# BUG exiftransfer wrong after reverse-order or block-evaluate
 
 usage() {
   echo "imfuse v$Version
@@ -193,17 +190,12 @@ Image comparision mask options: (Intended for artefact removal)
                         overlay interpolate colordodge hardlight reflect 
                         softburn softlight linearlight pegtoplight
  --enfuse [=ARG]      Image comparision with a basic enfuse result.
- --evaluate [=ARG]    Evaluates all source images with mode MODE.
-                      Compare ImageMagick option -evaluate-sequence.
+ --evaluate [=ARG]    Evaluates from all source images with mode MODE and
+                      compares the result with each source image.
                       ARG additionally takes arguments:
                         (word)   MODE                Default: max
                       MODE can be one of '$(basename $Magicklist) -list evaluate'
                       Compare --max, --min, --mean, --median.
-                      Most of interest:
-                        max      Brightest pixels in sequence. 
-                        mean     Average pixel values in sequence. 
-                        median   Middle pixel values in sequence. 
-                        min      Darkest pixels in sequence.
  --halo [=ARG]        Remove light halo of white background (overexposure).
                       ARG additionally takes arguments:
                         p        percent             Default: 25
@@ -220,11 +212,11 @@ Image comparision mask options: (Intended for artefact removal)
                       ARG additionally takes arguments:
                         (word)   An image file name
  --max [=ARG]         Same as --evaluate=max. Brightest pixels of stack.
-                      Result similar to --lightness.
+                      Result is similar to --lightness.
  --mean [=ARG]        Same as --evaluate=mean. Average of pixels in stack.
  --median [=ARG]      Same as --evaluate=median. Median pixel of stack.
  --min [=ARG]         Same as --evaluate=min. Darkest pixels of stack.
-                      Result similar to --darkness.
+                      Result is similar to --darkness.
                            
 Colorspace channel mask options: (Intended for artefact removal)
 (All are variations of --channel, most of interest is --saturation)
@@ -282,11 +274,11 @@ Mask generation and fusion adjustments:
                       setting one of r oder R to 12.
                       Percent p is a threshold value; --close is only applied
                       to contrast areas stronger than percent p.
- --cutblur [=SIGMA]   Blur cut masks in final montage. Default SIGMA: 2
+ --cutblur [=SIGMA]   Blur cut masks in final montage. Default SIGMA: 5
  --denoise [=%]       Experimental option to remove noise in low contrast areas.
                       The percent value is a threshold. 
                       Rather use --alpha or --finalblur.
- --fakehdr [=%]       Balances over- and underexposed areas. Default %: 50
+ --fakehdr [=%]       Balances over- and underexposed areas. Default %: 40
                       Remaining artefacts at borders of overexposured areas
                       might be fixed with --saturation. Alternative: --halo
  --finalblur [=p%,sSIGMA1,Ssigma2]   Soft blur of bokeh. Blurs low contrast 
@@ -470,6 +462,26 @@ lowercase() {
 md5cut() {
   # print last 6 digits
   md5sum <<< "${1:-}" | cut -c27-32
+}
+parse_percent() {
+  local Percent
+  Percent="${1:-}"
+  Percent="$(tr -d 'p%' <<< "$Percent")"
+  [ "$Percent" = "$(digitonly "$Percent")" ] || {
+    error "Invalid percent value: ${1:}"
+    return 1
+  }
+  echo "$Percent"
+}
+parse_sigma() {
+  local Sigma
+  Sigma="${1:-}"
+  Sigma="$(tr -d 'sS' <<< "$Sigma")"
+  [ "$Sigma" = "$(digitonly "$Sigma")" ] || {
+    error "Invalid sigma value: ${1:}"
+    return 1
+  }
+  echo "$Sigma"
 }
 percentrm() {
   # remove % from string
@@ -1066,6 +1078,7 @@ finalblur() {
     -delete 0"
     Command="$Command
   mpr:resultimage
+    -alpha off
     -blur 0x$Sigma1
     -write mpr:bokeh
     -delete 0
@@ -2592,8 +2605,6 @@ focus_maskmethod() {
     
   case $Method in
     blur)
-      # Concept and result is similar to Difference of Gaussian (DoG). Using -gaussian-blur gives same as DoG.
-      # Code based on https://im.snibgo.com/simpalign.htm#twoBlrDiff.bat
       Maskgenerator="
   mpr:sourcegray
     -blur ${Argradius1:-0}x${Argsigma1:-0.75}
@@ -2606,6 +2617,8 @@ focus_maskmethod() {
     -colorspace ${Argword1:-HSB} 
     -channel ${Argword2:-1} -separate
     +channel"
+      [ "$Method" = "darkness" ] && Maskgenerator="$Maskgenerator
+    -negate"
     ;;
     comet) ### FIXME saturate drops some angles
       Maskgenerator="
@@ -3416,7 +3429,7 @@ parse_options() {
   Shortoptions="ho:vVW"
   Longoptions="basename:,cache::,exif::,force::,help,output:,showimage,showname,test::,threads:,verbose,version,video"
   Longoptions="$Longoptions,alpha::,bg::,background::,close::,cutblur::,denoise::,fakehdr::,finalblur::,grayscale:,layers::,less::,maskblur::,prefertop::,redist::,revert,sigmoidalclut::,soft::,threshold::"
-  Longoptions="$Longoptions,channel::,chroma::,compose::,darkness::,enfuse::,evaluate::,halo::,image::,lightness::,max::,saturation::"
+  Longoptions="$Longoptions,channel::,chroma::,compose::,darkness::,enfuse::,evaluate::,halo::,image::,lightness::,max::,mean::,median::,min::,saturation::"
   Longoptions="$Longoptions,blur::,comet::,compass::,diffstat::,dog::,enfuse::,gaussian::,freichen::,kirsch::,laplacian::,log::,morphology::,none::,prewitt::,roberts::,sobel::,statistic::,unsharp::,wavelet::"  
   Longoptions="$Longoptions,experimental::,free::,freediff::"
   
@@ -3547,7 +3560,6 @@ $(grep -m1 ' ' <<< "$Sourceimagelist")"
         #Argmethod="channel"
         Argword1="HSL"
         Argword2="2"
-        Argnegate="yes"
       ;;
       evaluate)
         Image_needlist="$Image_needlist $Argword1"
@@ -3660,7 +3672,8 @@ $(grep -m1 ' ' <<< "$Sourceimagelist")"
   esac
   
   # --cutblur
-  [ "$Cutblur" = "auto" ] && Cutblur="1"
+  [ "$Cutblur" = "auto" ] && Cutblur="5"
+  [ "$Cutblur" ] && Cutblur="$(parse_sigma "$Cutblur")"
   
   # --denoise
   case $Globaldenoise in
@@ -4047,16 +4060,16 @@ main() {
       *)  focus_soft    --maskmax "$Resultmask" --output "$Resultimage" --alpha "$Globalalpha" --sigmoidal "$Softmode"     || error "Error in focus_soft" ;;
     esac
     [ "$Error" ] && return 1
-    # --alpha=ARG
-    [ "$Globalalpha" ] && {
-      note "Applying --alpha=$Globalalpha"
-      alphalevel --image "$Resultimage" --mask "$Resultmask" --level "$Globalalpha" || error "Error in leveling --alpha='$Globalalpha'"
-      [ "$Error" ] && return 1
-    }
     # --finalblur
     [ "$Finalblur" ] && {
       note "Applying --finalblur=p${Finalblurpercent},s${Finalblursigma1},S${Finalblursigma2}"
       finalblur --image "$Resultimage" --mask "$Resultmask" --percent "$Finalblurpercent" --sigma1 "$Finalblursigma1" --sigma2 "$Finalblursigma2" || error "Error in --finalblur"
+      [ "$Error" ] && return 1
+    }
+    # --alpha=ARG
+    [ "$Globalalpha" ] && {
+      note "Applying --alpha=$Globalalpha"
+      alphalevel --image "$Resultimage" --mask "$Resultmask" --level "$Globalalpha" || error "Error in leveling --alpha='$Globalalpha'"
       [ "$Error" ] && return 1
     }
     # --threshold
