--fusemode: 1...4

diff --git a/imfuse b/imfuse
--- a/imfuse
+++ b/imfuse
@@ -187,7 +187,7 @@ General mask generation adjustments:
                              Interesting results, but not exactly real.
                              - Fuse mode 3 uses semi-transparent layers with
                              sharpest layers topmost. Soft result with decreased
-                             contrast and no artefacts.
+                             contrast and free of noise artefacts.
      --grayscale=ARG         Grayscale converting method before mask generation.
                              Compare IM options -grayscale and -intensity.
                              ARG is one of: (number or name)
@@ -920,9 +920,11 @@ Contrastmaxlevel=%[fx:maxima*100]
   
   #Meandiff=$Cachedir/mean.tif
   #evaluate_split mean $Meandiff $Sourceimagelist
-  Masknumber="$((Masknumber+1))"
+  #Masknumber="$((Masknumber+1))"
   Overlaydiff=$Cachedir/overlay.tif
   #compose_stack overlay $Overlaydiff $Sourceimagelist
+
+  [ -e "$Softresult" ] && Masknumber="$((Masknumber+1))"
       
   Startzeit="$(date +%s)"
   Count=0
@@ -972,6 +974,16 @@ $Magickbin
   ( $Denoisemask
     +level 0%,$((Denoiseweight/Masknumber))% )
     -compose screen -composite"
+    # --fusemode 4
+    [ -e "$Softresult" ] && Command="$Command
+  ( $Softresult 
+  $Sourceimage 
+    -compose Difference -composite 
+    -grayscale RMS 
+    -negate 
+    +level 0%,$((50/Masknumber))% ) 
+    -compose screen -composite"
+    
 false && Command="$Command
   ( $Meandiff $Sourceimage -compose Difference -composite -grayscale RMS -negate +level 0%,$((50/Masknumber))% -write $Testimage ) -compose screen -composite"
 false && Command="$Command
@@ -985,6 +997,7 @@ false && Command="$Command
     #    +level 1%,99% 
     #    -write mpr:sourcemask
     #    -delete 0"
+    
     # --threshold
     [ "$Threshold" ] && Command="$Command
   mpr:sourcemask
@@ -1020,8 +1033,9 @@ $(grep "\S" <<< "$Command")"
   
   return ${Error:-0}
 }
-focus_fuse_mode1() {
-  # Fuse images
+focus_fuse_mode2() {
+  # --fusemode=2
+  # Fuse images, hard contrast
 
   local Sourcemask
   local Count Number
@@ -1145,7 +1159,114 @@ $(grep "\S" <<< "$Command")"
        
   return "${Error:-0}"
 }
-focus_fuse_mode2() {
+focus_fuse_mode3() {
+  # Soft focus stacking with semi-transparent layers
+  # --fusemode=3
+
+  local Resulttop Resultbottom
+  local Count Number
+  local Command
+  local Startzeit Dauer Restzeit
+  
+  Resulttop="$Cachedir/resulttop.tif"
+  Resultbottom="$Cachedir/resultbottom.tif"
+  $Magickbin -size ${Imagewidth}x${Imageheight} xc:blue -transparent blue -type TrueColorAlpha $Tifstore $Resulttop
+  $Magickbin -size ${Imagewidth}x${Imageheight} xc:blue -transparent blue -type TrueColorAlpha $Tifstore $Resultbottom
+  $Magickbin -size ${Imagewidth}x${Imageheight} xc:black -type Grayscale $Tifstore $Maskmax
+  
+  Startzeit="$(date +%s)"
+  Count=0    
+  for Sourceimage in $Sourceimagelist; do
+    [ "$Error" ] && break
+    Count="$((Count+1))"
+    Number="$(printnum $Count $Imagenumberlength)"
+    Sourcemask="$Cachedir/mask.${Number}.tif"
+    
+    Command="
+$Magickbin
+  $Sourceimage
+    -write mpr:sourceimage
+    -delete 0
+  $Sourcemask
+    -write mpr:sourcemask
+    -delete 0
+  $Maskmax
+    -write mpr:maxmask
+    -delete 0
+  $Resulttop
+    -write mpr:resultimagetop
+    -delete 0
+  $Resultbottom
+    -write mpr:resultimagebottom
+    -delete 0
+  mpr:sourcemask 
+  mpr:maxmask 
+    -evaluate-sequence max
+    -write mpr:maxmask
+    -write $Maskmax
+    -delete 0
+  mpr:sourcemask 
+  mpr:maxmask
+    -compose MinusDst -composite -fill white +opaque black -negate
+    -write mpr:cutmask
+   -delete 0
+  mpr:sourcemask 
+  mpr:cutmask
+    -alpha off -compose CopyOpacity -composite
+    -write mpr:sourcemaskpart
+    -delete 0
+  mpr:sourceimage 
+  mpr:sourcemaskpart
+    -alpha off -compose CopyOpacity -composite
+    -background blue -fill blue -alpha background
+    -write mpr:semitransparent
+    -delete 0
+  mpr:resultimagetop
+  mpr:semitransparent
+    -compose Over -composite
+    -type TrueColorAlpha
+    -write mpr:resultimagetop
+    -write $Resulttop
+    -delete 0
+  mpr:sourcemask 
+  ( mpr:cutmask -negate )
+    -alpha off -compose CopyOpacity -composite
+    -write mpr:sourcemaskpart
+    -delete 0
+  mpr:sourceimage 
+  mpr:sourcemaskpart
+    -alpha off -compose CopyOpacity -composite
+    -write mpr:semitransparent
+    -delete 0
+  mpr:resultimagebottom 
+  mpr:semitransparent
+    -compose Over -composite
+    -type TrueColorAlpha
+    -write mpr:resultimagebottom
+    -write $Resultbottom
+    -delete 0
+  mpr:resultimagebottom
+  mpr:resultimagetop
+    -compose Over -composite
+    -type TrueColorAlpha
+  $Resultimage"
+          
+    [ "$Count" = "1" ] && verbose "Fusing with:
+$(grep "\S" <<< "$Command")"
+
+    $Command || error "Error in fuse mode 3"
+    
+    showimage $Resultimage
+    Dauer="$(( $(date +%s)-Startzeit))"
+    Restzeit="$(( Dauer*(Imagenumber-Count) / Count ))"
+    verbose "$Method $Count/$Imagenumber. Duration: $(date -u -d @$Dauer +"%T"); estimated time left: $(date -u -d @$Restzeit +"%T")"
+  done
+  
+  $Magickbin $Resultimage -alpha off $Resultimage
+  
+  return "${Error:-0}"
+}
+focus_fuse_mode4() {
   # --fusemode=2: Compare on each step if source or result seem to be more sharp
   # Based on snibgo's focus stacking script at http://im.snibgo.com/focstack.htm
 
@@ -1199,115 +1320,6 @@ $(grep "\S" <<< "$Command")"
   done
   
   return ${Error:-0}
-}
-focus_fuse_mode3() {
-  # Soft focus stacking with semi-transparent layers
-  # --fusemode=3
-
-  local Resulttop Resultbottom
-  local Count Number
-  local Command
-  local Startzeit Dauer Restzeit
-  
-  Resulttop="$Cachedir/resulttop.tif"
-  Resultbottom="$Cachedir/resultbottom.tif"
-  $Magickbin -size ${Imagewidth}x${Imageheight} xc:blue -transparent blue -type TrueColorAlpha $Tifstore $Resulttop
-  $Magickbin -size ${Imagewidth}x${Imageheight} xc:blue -transparent blue -type TrueColorAlpha $Tifstore $Resultbottom
-  $Magickbin -size ${Imagewidth}x${Imageheight} xc:black -type Grayscale $Tifstore $Maskmax
-  
-  Startzeit="$(date +%s)"
-  Count=0    
-  for Sourceimage in $Sourceimagelist; do
-    [ "$Error" ] && break
-    Count="$((Count+1))"
-    Number="$(printnum $Count $Imagenumberlength)"
-    Sourcemask="$Cachedir/mask.${Number}.tif"
-    
-    Command="
-$Magickbin
-  $Sourceimage
-    -write mpr:sourceimage
-    -delete 0
-  $Sourcemask
-    -write mpr:sourcemask
-    -delete 0
-  $Maskmax
-    -write mpr:maxmask
-    -delete 0
-  $Resulttop
-    -write mpr:resultimagetop
-    -delete 0
-  $Resultbottom
-    -write mpr:resultimagebottom
-    -delete 0
-  mpr:sourcemask mpr:maxmask 
-    -evaluate-sequence max
-    -write mpr:maxmask
-    -write $Maskmax
-    -delete 0
-  mpr:sourcemask 
-  mpr:maxmask
-    -compose MinusDst -composite -fill white +opaque black -negate
-    -write mpr:cutmask
-     -write $Testimage
-   -delete 0
-  mpr:sourcemask 
-  mpr:cutmask
-    -alpha off -compose CopyOpacity -composite
-    -write mpr:sourcemaskpart
-    -delete 0
-  mpr:sourceimage 
-  mpr:sourcemaskpart
-    -alpha off -compose CopyOpacity -composite
-    -background blue -fill blue -alpha background
-    -write mpr:semitransparent
-    -alpha off
-    -delete 0
-  mpr:resultimagetop
-  mpr:semitransparent
-    -compose Over -composite
-    -type TrueColorAlpha
-    -write mpr:resultimagetop
-    -write $Resulttop
-    -delete 0
-  mpr:sourcemask 
-  ( mpr:cutmask -negate )
-    -alpha off -compose CopyOpacity -composite
-    -write mpr:sourcemaskpart
-    -delete 0
-  mpr:sourceimage 
-  mpr:sourcemaskpart
-    -alpha off -compose CopyOpacity -composite
-    -write mpr:semitransparent
-    -delete 0
-  mpr:resultimagebottom 
-  mpr:semitransparent
-    -compose Over -composite
-    -type TrueColorAlpha
-    -write mpr:resultimagebottom
-    -write $Resultbottom
-    -delete 0
-  mpr:resultimagebottom
-  mpr:resultimagetop
-    -compose Over -composite
-    -type TrueColorAlpha
-    -write $Testimage
-  $Resultimage"
-          
-    [ "$Count" = "1" ] && verbose "Fusing with:
-$(grep "\S" <<< "$Command")"
-
-    $Command || error "Error in fuse mode 3"
-    
-    showimage $Resultimage
-    Dauer="$(( $(date +%s)-Startzeit))"
-    Restzeit="$(( Dauer*(Imagenumber-Count) / Count ))"
-    verbose "$Method $Count/$Imagenumber. Duration: $(date -u -d @$Dauer +"%T"); estimated time left: $(date -u -d @$Restzeit +"%T")"
-  done
-  
-  $Magickbin $Resultimage -alpha off $Resultimage
-  
-  return "${Error:-0}"
 }
 focus_sharpness_layer() {
   # --layers: Layered TIF with sharpness layers
@@ -1444,6 +1456,7 @@ declare_variables() {
   Preservecache="no"
   Saturationweight=""
   Showimageprocessing="no"
+  Softresult=""
   Sourceimage=""
   Sourceimagelist=""
   Sourcemasklist=""
@@ -1532,10 +1545,11 @@ check_options() {
       [ "$Fusemode" ] && error "--fusemode has no effect with --$Method" ;;
     *)
       case $Fusemode in
-        ""|"1"|"auto") 
+        ""|"auto") 
           Fusemode="1" 
         ;;
-        "2") 
+        1|2|3) ;;
+        4) 
           [ -z "${Method}${Radius1}" ] && {
             Method="statistic"
             Maskgeneratorargument="standarddeviation"
@@ -1544,10 +1558,9 @@ check_options() {
           } || {
             note "--fusemode=$Fusemode needs manual setting of parameters
   like --radius and --sigma.
-  Default values are often less useable and optimized for --fusemode=1."
+  Default values are often less useable and optimized for --fusemode=1, 2 and 3."
           }
         ;;
-        "3") ;;
         *) error "--fusemode: Unknown mode $Fusemode" ;;
       esac
     ;;
@@ -2015,8 +2028,8 @@ check_options() {
       compose|evaluate) ;;
       *)
         case $Fusemode in
-          1) ;;
-          *) Resultimage="${Resultimage}.m$Fusemode" ;;
+          XXX1) ;;
+          *) Resultimage="${Resultimage}.f$Fusemode" ;;
         esac
         [ "${Contrastweight}${Saturationweight}${Chromaweight}${Darknessweight}${Lightnessweight}" != "1000000" ] && {
           Resultimage="${Resultimage}."
@@ -2158,8 +2171,20 @@ main() {
       [ "$Error" ] && return 1
       focus_merge_masks
       [ "$Error" ] && return 1
-      focus_fuse_mode${Fusemode}
-      [ "$Error" ] && return 1
+      
+      case $Fusemode in
+        2) focus_fuse_mode2 || return 1 ;;
+        3) focus_fuse_mode3 || return 1 ;;
+        4) focus_fuse_mode4 || return 1 ;;
+        1)
+          Softresult="$Cachedir/softresult.tif"
+          focus_fuse_mode3  || return 1
+          cp $Resultimage $Softresult
+          focus_merge_masks || return 1
+          $Magickbin -size ${Imagewidth}x${Imageheight} xc:blue -transparent blue -type TrueColorAlpha $Tifstore $Resultimage || error "Failed to create transparent base image."
+          focus_fuse_mode2  || return 1
+        ;;
+      esac
       [ "$Storelayers" ] && focus_sharpness_layer
     ;;
   esac
