major change: equalize masks with redist

diff --git a/imfuse b/imfuse
--- a/imfuse
+++ b/imfuse
@@ -1,7 +1,7 @@
 #! /bin/bash
 
 # imfuse
-Version="0.6.5.0-beta"
+Version="0.6.6.0-beta"
 
 usage() {
   echo "imfuse v$Version
@@ -839,103 +839,65 @@ $Magickbin
   
   return "${Error:-0}"
 }
-level_check() {
-  local Maskmax Maskmin Level
-  local Histogramm Threshold Threshold_pixel Pixelnumber Pixelcount
-  local Maxpossible Minpossible
-
-  Level="$(maskarg_defaultvalue $Argmethod level)"
-  [ "$Level" ] && {
-    #Arglevelmin="$(cut -d, -f1 <<< "$Level" | tr -d '%')"
-    #Arglevelmax="$(cut -d, -f2 <<< "$Level" | tr -d '%')"
-    note "level_check(): default: $Level for $Argbasename"
-    #return 0
-  }
-  
-  Maskmax=$Cachedir/$Argbasename-max.tif
-  Maskmin=$Cachedir/$Argbasename-min.tif
-
-  evaluate max $Maskmax $(masklist "$Argbasename") || return 1
-  Arglevelmax="$($Magickbin "$Maskmax" -format '%[fx:maxima*100]' info:)"
-  
-  #Arglevelmin="$(maskarg_defaultvalue $Argmethod levelmin)"
-  [ -z "$Arglevelmin" ] && {
-    evaluate min $Maskmin $(masklist "$Argbasename") || return 1
-    Arglevelmin="$($Magickbin "$Maskmin" -format '%[fx:minima*100]' info:)"
- }
-    
-  note "level_check(): ${Arglevelmin}%,${Arglevelmax}% for $Argbasename"
-  echo "level_check(): ${Arglevelmin}%,${Arglevelmax}% for $Argbasename" >> ~/.config/stackshots/level.results
-  
-  # eperimental
-  [ -z "$Argmaskstrength" ] && {   ### FIXME vulnerable check that masks has been leveled already
-    Maxpossible="$(maskarg_defaultvalue $Argmethod levelmax)"
-    Minpossible="$(maskarg_defaultvalue $Argmethod levelmin)"
-    [ "$Maxpossible" ] && [ "$Minpossible" ] && {
-      Argmaskstrength="$(calc "($Arglevelmax - $Arglevelmin) / ($Maxpossible - $Minpossible)")"
-    }
-  }
-  Argmaskstrength=1
-  
-  return ${Error:-0}
-}
 level_masks() {
-  local Maskmax Maskmin Maskmd5
+  local Maskmax Maskmin Maskmd5 Clutimage Resultmask
   local Startzeit Dauer Restzeit
   local Count Mask Masklist Levelmin Levelmax
   
-  case $# in
-    0)
-      Masklist="$(masklist "$Argbasename")"
-      Levelmin="$Arglevelmin"
-      Levelmax="$Arglevelmax"
-    ;;
-    *)
-      Masklist="$@"
-      Maskmd5="$(md5cut "$(ls --full-time $Masklist)" )"
-      Maskmax=$Cachedir/level-max.$Maskmd5.tif
-      Maskmin=$Cachedir/level-min.$Maskmd5.tif
-      #[ -e "$Maskmax" ] || {
-        evaluate max $Maskmax $Masklist || return 1
-      #}
-      #[ -e "$Maskmin" ] || {
-        evaluate min $Maskmin $Masklist || return 1
-      #}
-      Levelmax="$($Magickbin "$Maskmax" -format '%[fx:maxima*100]' info:)"
-      Levelmin="$($Magickbin "$Maskmin" -format '%[fx:minima*100]' info:)"
-    ;;
-  esac
   
-  [ "${Levelmin}%,${Levelmax}%" = "0%,100%" ] && {
-    verbose "Skipping level_masks(), already 0%,100%"
+  Masklist="$(masklist "$Argbasename")"
+  Maskmax="$Cachedir/$Argbasename-max.tif"
+  Maskmin="$Cachedir/$Argbasename-min.tif"
+  Clutimage="$Cachedir/$Argbasename-clut.miff"
+  
+  
+  Argbasename="level_$Argbasename"
+  maskarg_store
+  maskexist "$Argbasename" && {
+    verbose "level(): Already exists, skipping: $Argbasename"
     return 0
   }
+
+  evaluate max $Maskmax $Masklist || return 1
+  Levelmax="$($Magickbin "$Maskmax" -format '%[fx:maxima*100]' info:)"
+  Levelmin="$(maskarg_defaultvalue $Argmethod levelmin)"
+  [ -z "$Levelmin" ] && {
+    evaluate min $Maskmin $Masklist || return 1
+    Levelmin="$($Magickbin "$Maskmin" -format '%[fx:minima*100]' info:)"
+  }
+  verbose "level check: ${Levelmin}%,${Levelmax}% for $Argbasename"
+  
+  $Magickbin $Maskmax -level ${Levelmin}%,${Levelmax}% $Maskmax
+  redist $Maskmax $Clutimage
   
   Startzeit="$(date +%s)"
   Count=0
   for Mask in $Masklist ; do
     [ "$Error" ] && break
     Count="$((Count+1))"
-            
+    
+    Resultmask="$(sed "s%.*/%&level_%" <<< "$Mask")"
     Command="
 $Magickbin
   $Mask
     -level ${Levelmin}%,${Levelmax}%
-  $Mask"
+  $Clutimage
+    -clut
+    $Tifstore 
+  $Resultmask"
   
   [ "$Count" = "1" ] && verbose "Leveling masks with:
 $(grep "\S" <<< "$Command")"
   
     #$Command || error "Failure in leveling $Argmethod masks"
-    multicore "$Command" || error "Failure in leveling masks"
+    multicore "$Command" "$Resultmask" || error "Failure in leveling masks"
   
-    showimage "$Mask"
     Dauer="$(( $(date +%s)-Startzeit))"
     Restzeit="$(( Dauer*(Imagenumber-Count) / Count ))"
     verbose "Leveling $Count/$Imagenumber. Duration: $(date -u -d @$Dauer +"%T"); ETA: $(date -u -d @$Restzeit +"%T")"
   done
   multicore_wait || error "Failure in leveling masks"
-  [ "$Testsetup" ] && redist
+
   return "${Error:-0}"
 }
 maskfromimage() {
@@ -1016,36 +978,29 @@ mkimg_transparent() {
   $Magickbin -size $Size canvas:transparent -type TrueColorAlpha ${1:-transparent.tif}"
   $Magickbin -size "$Size" canvas:transparent -type TrueColorAlpha "${1:-transparent.tif}"
 }
-
 redist() {
-  local Masklist Maskmd5 Maskmax Clutimage
+  local Maskmax Clutimage
   local histArr ccountArr totpix maxval fact lutlist
-  case $# in
-    0) Masklist="$(masklist "$Argbasename")" ;;
-    *) Masklist="$@" ;;
-  esac
   
-  Maskmd5="$(md5cut "$(ls --full-time $Masklist)" )"
-  Maskmax=$Cachedir/redist-max.$Maskmd5.tif
-  evaluate max $Maskmax $Masklist || return 1
+  Maskmax="${1:-}"
+  Clutimage="${2:-}"
       
   maxval=65535
 
-  Clutimage="$Cachedir/clut.$Maskmd5.miff"
+  #Clutimage="$Cachedir/clut.$Maskmd5.miff"
 
   #cumHistogram 
-  histArr=(`convert $Maskmax -colorspace gray -depth 8 -format "%c" histogram:info:- \
-  | sed -n 's/[ ]*\([0-9]*\).*gray[(]\([0-9]*\).*$/\1 \2/p' |\
-  awk '
-  # AWK to generate a zero filled histogram
-  { bin[int($2)] += $1; } 
-  END { for (i=0;i<256;i++) {hist = bin[i]+0; print hist; }
-  } '`)
+  histArr=($($Magickbin $Maskmax -colorspace gray -depth 8 -format "%c" histogram:info:- \
+             | sed -n 's/[ ]*\([0-9]*\).*gray[(]\([0-9]*\).*$/\1 \2/p' \
+             | awk '# AWK to generate a zero filled histogram
+                    { bin[int($2)] += $1; } 
+                    END { for (i=0;i<256;i++) {hist = bin[i]+0; print hist; }
+                    } ' ))
 
-  ccountArr=(`echo ${histArr[*]} |\
-  awk '# AWK to generate a cumulative histogram
-  { split($0,count," ") }
-  END { for (i=0;i<256;i++) { cum += count[i]; print cum } } '`)
+  ccountArr=($(echo ${histArr[*]} \
+               | awk '# AWK to generate a cumulative histogram
+                      { split($0,count," ") }
+                      END { for (i=0;i<256;i++) { cum += count[i]; print cum } }' ))
   totpix=${ccountArr[255]}
   
   
@@ -1054,22 +1009,16 @@ redist() {
   # the uniform distribution has an integral which is f(x)=x
   # this means that the cumulative distribution of the image is its own lut and only needs to be scaled
   # get raw cumulative histogram
-  fact=`convert xc: -format "%[fx:$maxval/$totpix]" info:`
-  lutlist=$(for ((i=0; i<256; i++)); do
+  fact="$($Magickbin xc: -format "%[fx:$maxval/$totpix]" info:)"
+  lutlist="$(for ((i=0; i<256; i++)); do
     echo "${ccountArr[$i]}"
-  done |\
-  awk -v fact="$fact" '{ print int(fact*$1); }')
+  done | awk -v fact="$fact" '{ print int(fact*$1); }')"
   
   # now convert lutArr into lut image
   # Use NetPBM (PGM format implied intermediate image)
   # note, (somewhere in IM between 6.7.5.5 and 6.7.8.2) PGM is linear
 
-  echo "P2 256 1 $maxval $lutlist" | convert - -scale 256x1\! $Clutimage
-
-  for Image in $Masklist; do
-    $Magickbin $Image $Clutimage -clut $Image
-    showimage $Image
-  done
+  echo "P2 256 1 $maxval $lutlist" | convert - -scale 256x1\! "$Clutimage"
 }
 
 # core focus stack routines
@@ -1196,21 +1145,12 @@ $(grep "\S" <<< "$Command")"
     maskarg_parse "$Line"
     
     # get -level min/max values for contrast masks
-    [ "$Arglevel" = "yes" ] && {
-      level_check
-      maskarg_store
-      level_masks
-      Arglevel=
-      Arglevelmin=
-      Arglevelmax=
-      maskarg_store
-    }
+    [ "$Arglevel" = "yes" ] && level_masks
     
     [ "${Argless}" ] && [ "${Argsoft}" ] && {
       note "Generating soft&less image for mask $Argmethod"
       Imagename="$Cachedir/$Argbasename-prepare-less${Argless}-soft${Argsoft}-cb${Cutblur}.tif"
-      level_masks
-      focus_montage --soft "$Argsoft" --lessthanmax "$Argless" --maskstrength="${Argmaskstrength:-1}" --output "$Imagename" -- $(masklist "$Argbasename") || break
+      focus_montage --soft "$Argsoft" --lessthanmax "$Argless" --output "$Imagename" -- $(masklist "$Argbasename") || break
       #$Magickbin "$Enfusebaseimage" "$Imagename" -compose Over -composite "$Imagename" || error "Failed to compose soft result on enfuse background"
       Argbasename="$Argmethod-soft$Argsoft-less$Argless-cb$Cutblur.$(md5cut "$Argbasename $Argsoft $Argless $Cutblur" )"
       maskexist "$Argbasename" || {
@@ -1219,22 +1159,16 @@ $(grep "\S" <<< "$Command")"
         maskfromimage $Imagename $Cachedir/$Argbasename || break  ### FIXME issue with --cache
       }
       Arglevel=""
-      Argmaskstrength=""
       Argtype="image"
       maskarg_store      
     }
     
     [ "${Argless}" ] && [ -z "${Argsoft}" ] && {
-      [ "$Arglevel" = "yes" ] && level_masks
-      Arglevelmin=""
-      Arglevelmax=""
-      Arglevel=""
-      maskarg_store
       Imagename="$Cachedir/$Argbasename-prepare-less$Argless-cb${Cutblur}.tif"
       Maskmax="$Cachedir/$Argbasename-less${Argless}-cb$Cutblur.mask.tif"
       [ -e "$Maskmax" ] || {
         note "Generating less mask for $Argmethod"
-        focus_montage --lessthanmax "$Argless" --maskmax "$Maskmax" --maskstrength="${Argmaskstrength:-1}" --output "$Imagename" -- $(masklist "$Argbasename") || break   
+        focus_montage --lessthanmax "$Argless" --maskmax "$Maskmax" --output "$Imagename" -- $(masklist "$Argbasename") || break   
       }
       Argdarkenmask="$Maskmax"
       maskarg_store
@@ -1254,7 +1188,6 @@ focus_merge_masks() {
   
   Mergeneeded="no"
   [ "$Maskmethodnumber" -gt "1" ] && Mergeneeded="yes"
-  Mergeneeded=yes
 
   [ -z "$Maskmethodlist" ] && {
     note "Skipping mask merge, no mask options are specified."
@@ -1278,21 +1211,19 @@ focus_merge_masks() {
       
     Methodmask="$Cachedir/$Argbasename.NUMBER.tif"
       
-    [ "$Arglevel" ]                                         && Mergeneeded="yes" 
     [ "$Argdenoise" ]                                       && Mergeneeded="yes" 
     [ "$Argdarkenmask" ]                                    && Mergeneeded="yes" 
-    [ "$Argsoft" ]                                          && Mergeneeded="yes" 
+    #[ "$Argsoft" ]                                          && Mergeneeded="yes" 
     [ "$Argthreshold" ]                                     && Mergeneeded="yes" 
     [ "$Globalclose" ]                                      && Mergeneeded="yes"
-    [ "$Globalsoft" ]                                       && Mergeneeded="yes"
+    #[ "$Globalsoft" ]                                       && Mergeneeded="yes"
     [ "$Globaldenoise" ]                                    && Mergeneeded="yes"
     [ "$Testsetup" ]                                        && Mergeneeded="yes"
     [ "$Mergeneeded" = "no" ] && break
       
     Mergecode="$Mergecode
   ( 
-  $Methodmask
-    -level ${Arglevelmin:-0}%,${Arglevelmax:-100}%"
+  $Methodmask"
 
     ### FIXME might affect level
     [ "$Argmaskblur" ] && {
@@ -1308,12 +1239,12 @@ focus_merge_masks() {
   $Argdarkenmask
     -compose Darken -composite"
     
-    # denoise ###FIXME Maskstrength
+    # denoise
     [ "$Argdenoise" ] && Mergecode="$Mergecode $(denoisecode "$Argdenoise")"
     
-    # threshold ###FIXME Maskstrength
+    # threshold
     [ "$Argthreshold" ] && Mergecode="$Mergecode
-    -black-threshold $(calc "$Argthreshold /$Argmaskstrength")%"
+    -black-threshold $Argthreshold%"
     
     Mergecode="$Mergecode
     +level 0%,$(calc "(100 * ${Argweight:-100}) / (${Maskmethodnumber:-1} * $Weightmax)" )% 
@@ -1322,10 +1253,10 @@ focus_merge_masks() {
   done <<< "$Maskmethodlist"
   
   # denoise low contrast areas
-  [ "$Globaldenoise" ] && { ###FIXME Maskstrength
+  [ "$Globaldenoise" ] && {
     Mergecode="$Mergecode $(denoisecode "$Globaldenoise")"
     Mergemaskbasename="$Mergemaskbasename-denoise"
-  }   
+  }
   
   # --close
   [ "${Globalclose}" ] && {
@@ -1387,7 +1318,7 @@ focus_montage() {
 
   local Resultimage Resultfinalblur Outputimage Sourceimage Maskimagelist= Resultmd5
   local Lessthanmaxmask
-  local Maskmax Maskmaxcopy= Maskmaxready= Maskstrength=
+  local Maskmax Maskmaxcopy= Maskmaxready=
   local Count Number
   local Contrastmaxlevel Softfusion= Lessthanmax=
   local Command Skipmontage=
@@ -1406,7 +1337,6 @@ focus_montage() {
       --soft)         Softfusion="${2:-}"  ; shift ;;
       --lessthanmax)  Lessthanmax="${2:-}" ; shift ;;
       --maskmax)      Maskmaxcopy="${2:-}" ; shift ;;
-      --maskstrength) Maskstrength="${2:-}" ; shift ;;
       --) ;;
       *)              Maskimagelist="$Maskimagelist ${1:-}" ;;
     esac
@@ -1435,17 +1365,11 @@ focus_montage() {
     mkimg_transparent "$Resultimage"
     mkimg_black       $Maskmax
   
-    #[ "$Softfusion" ] && level_masks $Maskimagelist
-    [ "$Softfusion" ] && {
-      Softfusion="$(calc "$Softfusion /${Maskstrength:-1}")"
-    }
-  
     [ "$Lessthanmax" ] && {
       evaluate max $Maskmax $Maskimagelist || return 1
       Maskmaxready="yes"
       Contrastmaxlevel="$($Magickbin $Maskmax -format '%[fx:maxima*100]' info:)"
       Lessthanmax="$(calc "$Lessthanmax*$Contrastmaxlevel/100")"
-      Lessthanmax="$(calc "$Lessthanmax/${Maskstrength:-1}")"
       Lessthanmaxmask="$Cachedir/lessthanmax.tif"
       mkimg_black "$Lessthanmaxmask"
     }
@@ -1511,7 +1435,7 @@ $Magickbin
     -delete 0"
     
     # drop areas with contrast=0
-    [ "$Background" ] && Command="$Command   
+    false && [ "$Background" ] && Command="$Command   
   mpr:cutmask
   ( mpr:sourcemask -threshold 0% )
     -compose Darken -composite
@@ -1700,7 +1624,7 @@ $(grep "\S" <<< "$Command")"
     -write mpr:maskmax
     -delete 0
   mpr:maskmax
-    -threshold $(calc "${Finalblurpercent:-10} /${Maskstrength:-1}")%
+    -threshold ${Finalblurpercent:-10}%
     -negate
     -write mpr:cutmask
     -delete 0
@@ -2031,9 +1955,6 @@ maskarg_parse() {
   Argdiff=""
   Argless=""
   Arglevel=""
-  Arglevelmin=""
-  Arglevelmax=""
-  Argmaskstrength=""
   #Argmethod=""
   Argnegate=""
   Argpercent1=""
@@ -2087,11 +2008,8 @@ maskarg_parse() {
       "CLOSE1")           Argclose1="$Value" ;;
       "CLOSE2")           Argclose2="$Value" ;;
       "LEVEL")            Arglevel="yes" ;;
-      "LEVELMIN")         Arglevelmin="$Value" ;;
-      "LEVELMAX")         Arglevelmax="$Value" ;;
       "DARKENMASK")       Argdarkenmask="$Value" ;;
       "NUM")              Maskmethodcount="$Value" ;;
-      "STRENGTH")         Argmaskstrength="$Value" ;;
       "METHOD")           Argmethod="$Value" ;;
       "TYPE")             Argtype="$Value" ;;
       "BASENAME")         Argbasename="$Value" ;;
@@ -2128,9 +2046,6 @@ maskarg_store() {
   [ "$Argswap" ]               && Newoption="$Newoption,swap"
   [ "$Argdarkenmask" ]         && Newoption="$Newoption,DARKENMASK=$Argdarkenmask"
   [ "$Arglevel" ]              && Newoption="$Newoption,LEVEL"
-  [ "$Arglevelmin" ]           && Newoption="$Newoption,LEVELMIN=$Arglevelmin"
-  [ "$Arglevelmax" ]           && Newoption="$Newoption,LEVELMAX=$Arglevelmax"
-  [ "$Argmaskstrength" ]       && Newoption="$Newoption,STRENGTH=$Argmaskstrength"
   [ "$Argtype" ]               && Newoption="$Newoption,TYPE=$Argtype"
   [ "$Argbasename" ]           && Newoption="$Newoption,BASENAME=$Argbasename"
 
@@ -2156,7 +2071,8 @@ maskarg_defaultvalue() {
       esac
     ;;
     less)
-      case "${1:-}" in
+      echo "10"
+      false && case "${1:-}" in
         blur)       echo "8" ;;
         comet)      echo "6" ;;
         compass)    echo "4" ;;
@@ -2175,41 +2091,6 @@ maskarg_defaultvalue() {
         #unsharp
         wavelet)    echo "35" ;;
         *)          echo "10" ;;
-      esac
-    ;;
-    level)
-      case "${1:-}" in
-        blur)       echo "0%,7.68292%" ;;
-        comet)      echo "0%,35.523%" ;;
-        compass)    echo "45.0599%,80.0015%" ;;
-        dog)        echo "0%,38.941%" ;;
-        diffstat)
-          case "$Argword1,$Argword2" in
-            "median,mean") echo "0%,44.1398%" ;;
-            "min,max")     echo "0%,100%" ;;
-          esac
-        ;;
-        freichen)   echo "33.6584%,100%" ;;
-        gaussian)   echo "0%,0.764477%" ;;
-        #kirsch)     echo "" ;;
-        laplacian)
-          case $Argword1 in
-            3)      echo "0%,18.6282%" ;;
-          esac
-        ;;
-        log)        echo "0%,37.5494%" ;;
-        morphology) echo "0%,100%" ;;
-        prewitt)    echo "34.3893%,100%" ;;
-        #roberts)    echo "7.64782%,100%" ;;
-        sobel)      echo "34.3893%,100%" ;;
-        statistic)
-          case $Argword1 in
-            standarddeviation) echo "0%,50.0008%" ;;
-          esac
-        ;;
-        #unsharp
-        wavelet)    echo "0%,12.8145%" ;;
-        *)          echo "" ;;
       esac
     ;;
     levelmin)
@@ -2247,43 +2128,9 @@ maskarg_defaultvalue() {
         *)          echo "" ;;
       esac
     ;;
-    levelmax)
-      case "${1:-}" in
-        blur)       echo "7.68292" ;;
-        comet)      echo "35.523" ;;
-        compass)    echo "80" ;;
-        dog)        echo "38.941" ;;
-        diffstat)
-          case "$Argword1,$Argword2" in
-            "median,mean") echo "44.1398" ;;
-            "min,max")     echo "100" ;;
-          esac
-        ;;
-        freichen)   echo "100" ;;
-        gaussian)   echo "0.764477" ;;
-        #kirsch)     echo "" ;;
-        laplacian)
-          case $Argword1 in
-            3)      echo "18.6282" ;;
-          esac
-        ;;
-        log)        echo "37.5494" ;;
-        morphology) echo "100" ;;
-        prewitt)    echo "100" ;;
-        #roberts)    echo "7.64782%,100%" ;;
-        sobel)      echo "100" ;;
-        statistic)
-          case $Argword1 in
-            standarddeviation) echo "50" ;;
-          esac
-        ;;
-        #unsharp
-        wavelet)    echo "12.8145" ;;
-        *)          echo "" ;;
-      esac
-    ;;
     noise)
-      case "${1:-}" in
+      echo "25"
+      false && case "${1:-}" in
         #blur)       echo "15" ;;
         #comet
         compass)    echo "25" ;;
@@ -2375,7 +2222,8 @@ maskarg_defaultvalue() {
       esac
     ;;
     soft)
-      case "${1:-}" in
+      echo "25"
+      false && case "${1:-}" in
         blur)       echo "25" ;;
         comet)      echo "30" ;;
         compass)    echo "35" ;;
@@ -2653,10 +2501,7 @@ declare_variables() {
   Argdiff=""
   Argless=""
   Arglevel=""
-  Arglevelmin=""
-  Arglevelmax=""
   Argmaskblur=""
-  Argmaskstrength=""
   Argmethod=""
   Argnegate=""
   Argpercent1=""
@@ -3290,8 +3135,7 @@ $Cachedir/fakehdr*.$(basename "$Image")"
   focus_generate_masks                    || return 1
   [ -n "$Maskmethodlist" ] && {
     focus_merge_masks                     || return 1
-    maskarg_parse "$(head -n1 <<< "$Maskmethodlist")"
-    focus_montage --soft "$Globalsoft" --lessthanmax "$Globalless" --maskstrength="${Argmaskstrength:-1}" --output "$Resultimage"  || return 1
+    focus_montage --soft "$Globalsoft" --lessthanmax "$Globalless" --output "$Resultimage"  || return 1
   }
 
   [ "$Background" ] && {
