suppress TIF exif warnings of IM #2

diff --git a/imfuse b/imfuse
--- a/imfuse
+++ b/imfuse
@@ -1,7 +1,7 @@
 #! /bin/bash
 
 # imfuse
-Version="0.6.1-beta"
+Version="0.6.2-beta"
 
 usage() {
   echo "imfuse v$Version
@@ -79,7 +79,7 @@ Contrast mask options:
                         r       radius               Default: 0
                         s       sigma                Default: 5
                         (word)  MODE                 Default: Lighten
-                      MODE can be one of '$(basename $Magickbin) -list compose'
+                      MODE can be one of '$(basename $Magicklist) -list compose'
                       Recommended: Lighten, Darken.
  --compass [=ARG]     Compass edge detection. 
  --dog [=ARG]         Difference of Gaussian. 
@@ -138,7 +138,7 @@ Contrast mask options:
                       ARG additionally takes arguments: 
                         r       radius               Default: 2
                         (word)  MODE                 Default: edge
-                      MODE can be one of '$(basename $Magickbin) -list morphology'
+                      MODE can be one of '$(basename $Magicklist) -list morphology'
                       Some MODEs of interest:
                         edge, dilateintensity, smooth
  --prewitt [=ARG]     Prewitt edge detection. 
@@ -176,7 +176,7 @@ Image comparision mask options: (Intended for artefact removal)
                         swap     Compose max,min instead of min,max
                                  Makes a difference for some, but not
                                  all compose MODEs.
-                      MODE can be one of '$(basename $Magickbin) -list compose'
+                      MODE can be one of '$(basename $Magicklist) -list compose'
                       Some MODEs of interest:
                         bumpmap colorburn difference linearburn 
                         linearlight modulate multiply overlay pegtoplight
@@ -185,7 +185,7 @@ Image comparision mask options: (Intended for artefact removal)
                       Compare ImageMagick option -evaluate-sequence.
                       ARG additionally takes arguments:
                         (word)   MODE                Default: max
-                      MODE can be one of '$(basename $Magickbin) -list evaluate'
+                      MODE can be one of '$(basename $Magicklist) -list evaluate'
                       Most of interest:
                         max      Brightest pixels in sequence. 
                         mean     Average pixel values in sequence. 
@@ -213,7 +213,7 @@ Colorspace channel mask options: (Intended for artefact removal)
                       ARG additionally takes arguments:
                         (word)   Colorspace           Default: HSL
                         (word)   Color channel        Default: 1
-                      Colorspace can be one of '$(basename $Magickbin) -list colorspace'
+                      Colorspace can be one of '$(basename $Magicklist) -list colorspace'
                       The color channel is a number from 0..31.
  --chroma             Chroma channel from HCL colorspace.
  --darkness           Negated lightness channel from HSL colorspace.
@@ -226,9 +226,9 @@ Mask generation and fusion adjustments:
  --background BG      Specify a background to paint on. Default: mean
                       BG can be an image name or one of:
                         saturation enfuse min max mean median
-                        $Magickbin -list color
-                        $Magickbin -list evaluate
-                        $Magickbin -list compose
+                        $Magicklist -list color
+                        $Magicklist -list evaluate
+                        $Magicklist -list compose
                       Well to combine with --soft. Possible use with threshold.
  --close [=ARG]       Closes gaps between nearby contrast lines to mark the 
                       area in between as strong contrast, too. Default: 2x2
@@ -343,7 +343,7 @@ calc() {
   awk "BEGIN {print $* }"
 }
 checkmagicklist() {
-  $Magickbin -list "${1:-}" | cut -d' ' -f1 | grep -q -x -i "${2:-XXX}"
+  $Magicklist -list "${1:-}" | cut -d' ' -f1 | grep -q -x -i "${2:-XXX}"
 }
 digitonly() {
   #sed "s/[^0-9.]//g" <<< "${1:-}"
@@ -1692,7 +1692,7 @@ mkimg_transparent() {
   local Size
   Size="${2:-}"
   [ -z "$Size" ] && Size="${Imagewidth:-100}x${Imageheight:-100}"
-  $Magickbin -size "$Size" xc:blue -transparent blue -type TrueColorAlpha $Tifstore "${1:-transparent.tif}" || error "Failed to create transparent image ${1:-}."
+  $Magickbin -size "$Size" xc:blue -transparent blue $Tifstorealpha "${1:-transparent.tif}" || error "Failed to create transparent image ${1:-}."
 }
 denoisecode() {
   echo "
@@ -1973,6 +1973,7 @@ declare_variables() {
   Layers=""
   Line=""
   Magickbin=""
+  Magicklist=""
   Magickpixelmemory=""
   Magickversion=""
   Maskmethodcount=""
@@ -2688,7 +2689,7 @@ maskarg_checkallowed() {
           Arg="$(lowercase "${Arg}")"
           checkmagicklist "$Method" "$Arg" || {
             error "--$Method=$Arg: unknown argument.
-  Please choose one out of '$Magickbin -list $Method'"
+  Please choose one out of '$Magicklist -list $Method'"
           }
         ;;
         diffstat)
@@ -2699,7 +2700,7 @@ maskarg_checkallowed() {
           Arg="$(lowercase "${Arg}")"
           Arg="$(maskarg_checkstatistic "$Arg")"
           [ "$Arg" = "source" ] && error "--$Method does not take argument $Arg
-  Please choose one out of '$Magickbin -list $Method'"
+  Please choose one out of '$Magicklist -list $Method'"
         ;;
         *) error "$Method does not take argument word1 $Arg" ;;
       esac
@@ -2805,13 +2806,13 @@ main() {
   
   command -v convert >/dev/null && Magickbin="convert"
   command -v magick  >/dev/null && Magickbin="magick"
-  Magickbin="nice $Magickbin"
   [ -z "$Magickbin" ] && error "Neither command convert nor magick found. Please install ImageMagick."
   Magickversion="$($Magickbin -version)"
   grep -q " Q8 "   <<< "$Magickversion" && Magickpixelmemory="4"
   grep -q " Q16 "  <<< "$Magickversion" && Magickpixelmemory="8"
   grep -q " HDRI " <<< "$Magickversion" && Magickpixelmemory="16"
-  [ "$Error" ] && return 1
+  Magicklist="$Magickbin"
+  Magickbin="nice $Magickbin -quiet"  [ "$Error" ] && return 1
   
   Freemem="$(freememory)"
   [ -z "$Freemem" ] && {
@@ -2927,9 +2928,9 @@ $Cachedir/fakehdr*.$(basename "$Image")"
       [ -f "$Background" ] && identify "$Background" && $Magickbin "$Background" "$Backgroundimage" || error "Option --background: Failed to load image '$Background'.
   Either specify an image or a color name or a mode out of:
     saturation
-    $Magickbin -list color
-    $Magickbin -list evaluate
-    $Magickbin -list compose"
+    $Magicklist -list color
+    $Magicklist -list evaluate
+    $Magicklist -list compose"
     ;;
   esac
   [ "$Error" ] && return 1
