mkimg_transparent(): create transparent image in another way #3

diff --git a/imfuse b/imfuse
--- a/imfuse
+++ b/imfuse
@@ -1,7 +1,7 @@
 #! /bin/bash
 
 # imfuse
-Version="0.6.2.1-beta"
+Version="0.6.2.2-beta"
 
 usage() {
   echo "imfuse v$Version
@@ -479,6 +479,9 @@ flatten() {
   Resultimage="${1:-}"
   shift
   
+  verbose "Flattening on:
+$(identify "$Resultimage")"
+  
   Command="$Magickbin
   $Resultimage
     -alpha set"
@@ -488,6 +491,9 @@ flatten() {
   $Image
     -compose Over -composite"
   done
+  
+  verbose "Flattening with:
+$Command"
   
   Command="$Command
     $Tifstorealpha
@@ -1692,9 +1698,12 @@ mkimg_transparent() {
   local Size
   Size="${2:-}"
   [ -z "$Size" ] && Size="${Imagewidth:-100}x${Imageheight:-100}"
+#  note "Generating transparent image with:
+#$Magickbin -size \"$Size\" xc:blue -transparent blue $Tifstorealpha \"${1:-transparent.tif}\""
+#  $Magickbin -size "$Size" xc:blue -transparent blue $Tifstorealpha "${1:-transparent.tif}" || error "Failed to create transparent image ${1:-}."
   note "Generating transparent image with:
-$Magickbin -size \"$Size\" xc:blue -transparent blue $Tifstorealpha \"${1:-transparent.tif}\""
-  $Magickbin -size "$Size" xc:blue -transparent blue $Tifstorealpha "${1:-transparent.tif}" || error "Failed to create transparent image ${1:-}."
+  $Magickbin -size \"$Size\" xc:transparent -type TrueColorAlpha \"${1:-transparent.tif}\""
+  $Magickbin -size "$Size" xc:transparent -type TrueColorAlpha "${1:-transparent.tif}"
 }
 denoisecode() {
   echo "
